/**
 * Texts of the material submittal module (zh / en). Kept here instead of context/LanguageContext.tsx so this module's
 * strings never mix with other modules' pending changes in that shared file (MATERIAL-SUBMITTAL M3 TASK).
 */
import { useCallback } from 'react';
import { useLanguage } from '../../context/LanguageContext';

const zh = {
    title: '材料',
    navTitle: '材料',
    selectProject: '請先在右上角選擇專案（核准材料以單一專案登錄與查詢）',
    chipAll: '全部',
    loaded: '已載入 {n}／共 {t} 筆',
    loadMore: '載入更多',
    loadFailed: '載入失敗，請重試。',
    retry: '重試',
    noPermission: '您沒有查看材料的權限。',
    // statuses / results
    'status.Draft': '草稿',
    'status.Submitted': '外部審查中',
    'status.Approved': '核准',
    'status.ApprovedWithComments': '附意見核准',
    'status.ReviseAndResubmit': '修正後再送',
    'status.Rejected': '拒絕',
    // columns / fields
    documentNumber: '送審編號',
    vendor: '承包商',
    materialName: '材料名稱',
    category: '分類',
    brand: '廠牌',
    model: '型號',
    specification: '規格',
    manufacturer: '製造商',
    supplier: '供應商',
    specReference: '依據（規範章節、圖說、契約條款）',
    overdue: '逾期',
    updatedAt: '最後更新',
    // detail
    snapshot: '送審內容（Rev {n} 快照）',
    upload: '上傳',
    deleteFile: '刪除',
    externalDocNo: '外部文件編號',
    // actions
    submit: '送交業主／顧問',
    close: '關閉',
    // dialogs
    resultCode: '審查結果',
    decisionMaker: '外部決定者（姓名）',
    // save / retry states (spec §9.3)
    saved: '已儲存',
    rejected: '未儲存：{d}',
    unconfirmed: '無法確認登錄結果。請稍後重新開啟本送審確認；系統不會自動重送。',
    loading: '載入中…',
    required: '必填',
    // naming rule
    namingDesc: '材料參考編號',
    approvedResult: '核准結果',
    approvedDate: '核准日',
    approvedMaterial: '材料',
    searchApproved: '搜尋編號、名稱、型號',
    photos: '材料照片',
    noPhotos: '尚無材料照片',
    viewTable: '表格',
    viewShelf: '展示架',
    uncategorised: '未分類',
    noPhotoShort: '尚無照片',
    photoCount: '{n} 張照片',
    shelfEmpty: '沒有符合的材料',
    enlargedPhoto: '放大檢視',
    fitScreen: '符合畫面',
    confirmDeletePhotoTitle: '刪除照片',
    confirmDeletePhotos: '儲存時將刪除 {n} 張照片，刪除後無法從畫面復原。確定要繼續嗎？',
    duplicateTitle: '可能重複登錄',
    exportExcel: '匯出 Excel',
    dashboardTotal: '核准材料總數',
    dashboardThisMonth: '本月新增 {n}',
    nothingToExport: '沒有可匯出的資料',
    exportFailed: '匯出失敗，請稍後再試',
    duplicateFound: '本專案已有相同名稱、廠牌、型號的材料：{list}。仍要儲存嗎？（例如不同承包商或不同批次核准）',
    saveAnyway: '仍要儲存',
    unknownRetrySafe: '連線中斷或逾時，無法確認是否已儲存，已重新讀取清單。可以直接再按一次儲存：系統會辨識同一筆，不會重複新增。',
    duplicateCheckFailedTitle: '無法完成重複檢查',
    duplicateCheckFailed: '目前無法檢查本專案是否已有相同名稱、廠牌、型號的材料。可以按「取消」稍後再按儲存重新檢查，或略過檢查直接儲存。',
    saveWithoutCheck: '略過檢查並儲存',
    approvalInfo: '核准資訊',
    materialInfo: '材料資料',
    openOriginal: '原圖',
    zoomHint: '雙擊切換 2 倍；＋／－ 縮放',
    registerNew: '新增材料',
    addNewMaterial: '新增材料',
    recordNo: '參考編號',
    registerEdit: '編輯材料',
    edit: '修改',
    externalApprovalNo: '外部核准文號',
    approvalResult: '核准結果',
    approvedBy: '核准者（外部決定者）',
    photosFailed: '資料已儲存，但照片上傳失敗：{d}',
    chooseVendor: '請選擇承包商',
};

const en: Record<keyof typeof zh, string> = {
    title: 'Material',
    navTitle: 'Material',
    selectProject: 'Choose a project at the top right first (approved materials are kept per project)',
    chipAll: 'All',
    loaded: 'Loaded {n} of {t}',
    loadMore: 'Load more',
    loadFailed: 'Failed to load. Please retry.',
    retry: 'Retry',
    noPermission: 'You do not have permission to view materials.',
    'status.Draft': 'Draft',
    'status.Submitted': 'Under external review',
    'status.Approved': 'Approved',
    'status.ApprovedWithComments': 'Approved with comments',
    'status.ReviseAndResubmit': 'Revise and resubmit',
    'status.Rejected': 'Rejected',
    documentNumber: 'Submittal No.',
    vendor: 'Contractor',
    materialName: 'Material',
    category: 'Category',
    brand: 'Brand',
    model: 'Model',
    specification: 'Specification',
    manufacturer: 'Manufacturer',
    supplier: 'Supplier',
    specReference: 'Basis (spec section, drawing, contract clause)',
    overdue: 'Overdue',
    updatedAt: 'Updated',
    snapshot: 'Submitted content (Rev {n} snapshot)',
    upload: 'Upload',
    deleteFile: 'Delete',
    externalDocNo: 'External doc. no.',
    submit: 'Submit to owner / consultant',
    close: 'Close',
    resultCode: 'Result',
    decisionMaker: 'External decision maker (name)',
    saved: 'Saved',
    rejected: 'Not saved: {d}',
    unconfirmed: 'The result could not be confirmed. Reopen this submittal later to check; nothing is re-sent automatically.',
    loading: 'Loading…',
    required: 'required',
    namingDesc: 'Material reference number',
    approvedResult: 'Result',
    approvedDate: 'Approved on',
    approvedMaterial: 'Material',
    searchApproved: 'Search no., name, model',
    photos: 'Material photos',
    noPhotos: 'No material photos yet',
    viewTable: 'Table',
    viewShelf: 'Shelf',
    uncategorised: 'Uncategorised',
    noPhotoShort: 'No photo',
    photoCount: '{n} photos',
    shelfEmpty: 'No matching materials',
    enlargedPhoto: 'Enlarged view',
    fitScreen: 'Fit screen',
    confirmDeletePhotoTitle: 'Delete photo',
    confirmDeletePhotos: 'Saving will delete {n} photo(s); this cannot be undone from the screen. Continue?',
    duplicateTitle: 'Possible duplicate',
    exportExcel: 'Export Excel',
    dashboardTotal: 'Approved materials',
    dashboardThisMonth: 'Registered this month {n}',
    nothingToExport: 'No data to export',
    exportFailed: 'Export failed; please try again',
    duplicateFound: 'This project already has a material with the same name, brand and model: {list}. Save anyway? (e.g. another contractor or another approval)',
    saveAnyway: 'Save anyway',
    unknownRetrySafe: 'Connection lost or timed out, so it is not certain the record was saved; the list has been re-read. You can simply press Save again: the system recognises the same record and will not add it twice.',
    duplicateCheckFailedTitle: 'Duplicate check failed',
    duplicateCheckFailed: 'The check for a material with the same name, brand and model in this project could not be done. Press Cancel and Save again later to re-check, or skip the check and save.',
    saveWithoutCheck: 'Skip check and save',
    approvalInfo: 'Approval',
    materialInfo: 'Material details',
    openOriginal: 'Original',
    zoomHint: 'Double-click for 2×; + / − to zoom',
    registerNew: 'Add Material',
    addNewMaterial: 'Add New Material',
    recordNo: 'Reference no.',
    registerEdit: 'Edit Material',
    edit: 'Edit',
    externalApprovalNo: 'External approval no.',
    approvalResult: 'Approval result',
    approvedBy: 'Approved by (external)',
    photosFailed: 'Saved, but the photo upload failed: {d}',
    chooseVendor: 'Choose a contractor',
};

export type MaterialTextKey = keyof typeof zh;

export function materialText(language: string, key: MaterialTextKey, params?: Record<string, string | number>): string {
    let s = (language === 'zh' ? zh : en)[key] ?? key;
    if (params) for (const [k, v] of Object.entries(params)) s = s.split(`{${k}}`).join(String(v));
    return s;
}

export function useMaterialText() {
    const { language } = useLanguage();
    return useCallback((key: MaterialTextKey, params?: Record<string, string | number>) => materialText(language, key, params), [language]);
}
