import React, { useState, useEffect } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { useContractors } from '../../context/ContractorsContext';
import styles from './Audit.module.css';

export interface AuditItem {
    id: string;
    auditNo: string;
    title: string;
    date: string;
    auditor: string;
    status: string;
    location: string;
    findings: string;
    contractor?: string;
}

interface AuditEditModalProps {
    auditId: string;
    existingItem?: AuditItem;
    onSave: (updates: Partial<AuditItem>) => void;
    onClose: () => void;
}

export const AuditEditModal: React.FC<AuditEditModalProps> = ({ auditId, existingItem, onSave, onClose }) => {
    const { t } = useLanguage();
    const { getActiveContractors } = useContractors();
    const activeContractors = getActiveContractors();

    const [formData, setFormData] = useState<Partial<AuditItem>>({
        auditNo: existingItem?.auditNo || '',
        title: existingItem?.title || '',
        date: existingItem?.date || '',
        auditor: existingItem?.auditor || '',
        status: existingItem?.status || 'Planned',
        location: existingItem?.location || '',
        findings: existingItem?.findings || '',
        contractor: existingItem?.contractor || '',
    });

    const handleFieldChange = (field: keyof AuditItem, value: string) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    };

    const handleSave = () => {
        onSave(formData);
        onClose();
    };

    return (
        <div className={styles.modalOverlay}>
            <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
                <div className={styles.modalHeader}>
                    <h2>{existingItem ? t('audit.editTitle') : t('audit.addTitle')}</h2>
                    <button className={styles.closeButton} onClick={onClose}>×</button>
                </div>
                <div className={styles.modalBody}>
                    <div className={styles.formSections}>
                        <div className={styles.formSection}>
                            <h3 className={styles.sectionTitle}>{t('common.baseInfo')}</h3>
                            <div className={styles.formGrid}>
                                <div className={styles.formGroup}>
                                    <label>{t('audit.auditNo')}</label>
                                    <input
                                        type="text"
                                        className={styles.formInput}
                                        value={formData.auditNo}
                                        readOnly
                                        disabled
                                        placeholder={t('form.autoGenerated')}
                                        style={{ backgroundColor: '#f3f4f6', cursor: 'not-allowed' }}
                                    />
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('common.contractor')}</label>
                                    <select
                                        className={styles.formSelect}
                                        value={formData.contractor}
                                        onChange={(e) => handleFieldChange('contractor', e.target.value)}
                                    >
                                        <option value="">{t('common.selectPlaceholder')}</option>
                                        {activeContractors.map(vendor => (
                                            <option key={vendor.id} value={vendor.name}>{vendor.name}</option>
                                        ))}
                                    </select>
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('audit.auditTitle')}</label>
                                    <input
                                        type="text"
                                        className={styles.formInput}
                                        value={formData.title}
                                        onChange={(e) => handleFieldChange('title', e.target.value)}
                                    />
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('audit.date')}</label>
                                    <input
                                        type={formData.date ? 'date' : 'text'}
                                        placeholder="mm/dd/yyyy"
                                        lang="en"
                                        onFocus={(e) => (e.target.type = 'date')}
                                        onBlur={(e) => {
                                            if (!e.target.value) e.target.type = 'text';
                                        }}
                                        className={styles.formInput}
                                        value={formData.date}
                                        onChange={(e) => handleFieldChange('date', e.target.value)}
                                    />
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('audit.location')}</label>
                                    <input
                                        type="text"
                                        className={styles.formInput}
                                        value={formData.location}
                                        onChange={(e) => handleFieldChange('location', e.target.value)}
                                    />
                                </div>
                                <div className={styles.formGroup}>
                                    <label>{t('audit.auditor')}</label>
                                    <input
                                        type="text"
                                        className={styles.formInput}
                                        value={formData.auditor}
                                        onChange={(e) => handleFieldChange('auditor', e.target.value)}
                                    />
                                </div>
                            </div>
                        </div>
                        <div className={styles.formSection}>
                            <h3 className={styles.sectionTitle}>{t('audit.sectionQuality')}</h3>
                            <div className={styles.formGrid}>
                                <div className={styles.formGroup}>
                                    <label>{t('common.status')}</label>
                                    <select
                                        className={styles.formSelect}
                                        value={formData.status}
                                        onChange={(e) => handleFieldChange('status', e.target.value)}
                                    >
                                        <option value="Planned">Planned</option>
                                        <option value="In Progress">In Progress</option>
                                        <option value="Completed">Completed</option>
                                        <option value="Closed">Closed</option>
                                    </select>
                                </div>
                                <div className={styles.formGroupFull}>
                                    <label className={styles.optionalLabel}>{t('audit.findings')}</label>
                                    <textarea
                                        className={styles.formTextarea}
                                        value={formData.findings}
                                        onChange={(e) => handleFieldChange('findings', e.target.value)}
                                        rows={4}
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.modalActions}>
                    <button className={styles.saveButton} onClick={handleSave}>
                        {t('common.save')}
                    </button>
                    <button className={styles.cancelButton} onClick={onClose}>
                        {t('common.cancel')}
                    </button>
                </div>
            </div>
        </div>
    );
};
