import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Login
    'login.welcome': 'Welcome Back',
    'login.subtitle': 'Enter your credentials to access Qualitas',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.failed': 'Failed to login. Please check your credentials.',

    // Common
    'common.edit': 'Edit',
    'common.details': 'Details',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.saveFailed': 'Save Failed',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.addDate': 'Add Date',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.loading': 'Loading...',
    'common.retry': 'Retry',
    'common.confirmDeleteTitle': 'Confirm Delete',
    'common.operations': 'Operations',
    'common.noData': 'No data found',
    'common.confirmDelete': 'Are you sure you want to delete this item?',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.status': 'Status',
    'common.vendor': 'Vendor',
    'common.contractor': 'Contractor',
    'common.title': 'Title',
    'common.referenceNo': 'Reference no.',
    'common.version': 'Version',
    'common.date': 'Date',
    'common.updatedDate': 'Updated Date',
    'common.createdDate': 'Created Date',
    'common.remark': 'Remark',
    'common.description': 'Description',
    'common.viewDetails': 'View Details →',
    'common.close': 'Close',
    'common.print': 'Print',
    'common.selectPlaceholder': 'Select',
    'common.tbc': 'TBC',
    'common.na': 'N/A',
    'common.today': 'Today',
    'common.contactInfo': 'Contact Info',
    'common.baseInfo': 'Base Information',
    'common.back': 'Back',
    'common.selectContractor': 'Please select a contractor',
    'common.selectDate': 'Please select a date',
    'common.fillAtLeastOne': 'Please fill in at least one item',
    'common.invalidStatusTransition': 'This status transition is not allowed',
    'common.attachments': 'Attachments',
    'common.uploadFiles': '+ Upload Files',
    'common.allContractors': 'All Contractors',
    'common.batchDelete': 'Batch Delete',
    'common.changeStatus': 'Change Status',
    'common.clearSelection': 'Clear Selection',
    'common.confirmDeleteMsg': 'Are you sure you want to delete this item?',
    'common.dueDate': 'Due Date',
    'common.exportExcel': 'Export Excel',
    'common.items': 'items',
    'common.noDataToExport': 'No data to export',
    'common.notGenerated': 'Not Generated',
    'common.selected': 'selected',
    'common.status.open': 'Open',
    'common.statistics': 'Statistics',
    'common.passRate': 'Pass Rate',
    'common.activity': 'Activity',
    'common.package': 'Package',

    // Home
    'home.welcome': 'Welcome',
    'home.adminUser': 'Admin User',
    'home.logout': 'Logout',
    'home.dashboard.description': 'Data Dashboard and Statistical Analysis',
    'home.kpi.description': 'Key Performance Indicators Management',
    'home.followup.description': 'Follow Up Issues',
    'home.pqp.description': 'Quality Plan Management',
    'home.itp.description': 'Inspection and Test Plan Management',
    'home.checklist.description': 'Quality Inspection Checklist Management',
    'home.noi.description': 'Inspection Notification Management',
    'home.itr.description': 'Inspection and Test Report',
    'home.osd.description': 'Overage Shortage Damage Management',
    'home.obs.description': 'Observation Record Management',
    'home.ncr.description': 'Non-conformance Report Management',
    'home.fat.description': 'Factory Acceptance Test',
    'home.audit.description': 'Audit',
    'audit.total': 'Total',
    'audit.schedule': 'Audit Schedule',
    'audit.totalAudits': 'Total Audits',
    'home.contractors.description': 'Contractor Information and Contact Management',
    'home.km.description': 'Knowledge Management System',
    'home.iam.description': 'Manage Users, Roles, and Permissions Settings',
    'home.ownerPerformance.description': 'Owner Performance Tracking and Analysis',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.pqpMaturity': 'PQP Maturity',
    'dashboard.qualityPlan': 'Quality Plan',
    'dashboard.completion': 'Completion',
    'dashboard.itpTotal': 'ITP Total',
    'dashboard.submitted': 'Submitted',
    'dashboard.approved': 'Approved',
    'dashboard.obsTotal': 'OBS Total',
    'dashboard.open': 'Open',
    'dashboard.closed': 'Closed',
    'dashboard.ncrTotal': 'NCR Total',
    'dashboard.noiTotal': 'NOI Total',
    'dashboard.itrTotal': 'ITR Total',
    'dashboard.pqpMaturityAnalysis': 'PQP Maturity Analysis',
    'dashboard.itpMaturityAnalysis': 'ITP Maturity Analysis',
    'dashboard.obsStatusAnalysis': 'OBS Status Analysis',
    'dashboard.ncrVendorAnalysis': 'NCR Vendor Analysis',
    'dashboard.ncrStatusAnalysis': 'NCR Status Analysis',
    'dashboard.kpiOverview': 'Key Performance Indicators',
    'dashboard.subtitle': 'Data Overview and Analysis',
    'dashboard.interactiveCharts': 'Interactive Charts',
    'dashboard.ncrStatusChart': 'NCR Status Chart',
    'dashboard.noiCount': 'NOI Count',
    'dashboard.noiTrendChart': 'NOI Trend Chart',
    'dashboard.upcomingTasks': 'Upcoming Tasks',

    // PQP
    'pqp.title': 'Quality Plan List',
    'pqp.addNew': 'Add New Quality Plan',
    'pqp.statusStats': 'Status Statistics',
    'pqp.statsTitle': 'Status Statistics',
    'pqp.total': 'Total',
    'pqp.approvedRate': 'Approved Rate',
    'pqp.referenceNo': 'Reference no.',
    'pqp.contractor': 'Contractor',
    'pqp.version': 'Version',
    'pqp.updatedDate': 'Updated Date',
    'pqp.allContractors': 'All Contractors',
    'pqp.allStatus': 'All Status',
    'pqp.startDate': 'Start Date',
    'pqp.endDate': 'End Date',
    'pqp.subject': 'Subject',
    'pqp.titleShort': 'PQP',
    'pqp.searchPlaceholder': 'Search PQP...',
    'pqp.createdDate': 'Created Date',
    'pqp.status.approved': 'Approved',
    'pqp.status.reject': 'Reject',
    'pqp.status.notSubmit': 'Not Submit',
    'pqp.status.underReview': 'Under Review',
    'pqp.editTitle': 'Edit PQP',
    'pqp.addTitle': 'Add PQP',
    'pqp.infoSection': 'Quality Plan Information',
    'pqp.refNoHint': '(Generated by system)',
    'pqp.revPlaceholder': 'Enter Rev5.0 or higher',
    'pqp.revFormatError': 'Please enter format like Rev5.0, Rev6.0',
    'pqp.revMinError': 'Custom version must be Rev5.0 or higher',
    'pqp.revSelectCustom': 'Rev5.0 or higher (Manual)',
    'pqp.saveError': 'Save failed, please try again later.',
    'pqp.saving': 'Saving...',
    'pqp.titleRequired': 'Subject is required',
    'pqp.vendorRequired': 'Contractor is required',
    'pqp.versionRequired': 'Version is required',
    'pqp.remark': 'Remark',
    'pqp.addDate': 'Add Date',
    'pqp.detail.title': 'PQP Details',
    'pqp.tooltip.edit': 'Edit',
    'pqp.tooltip.details': 'Details',
    'pqp.tooltip.delete': 'Delete',
    'pqp.reviewITP': 'Review ITP',
    'pqp.relatedNOI': 'Related NOI',
    'pqp.confirmDeleteMessage': 'Are you sure you want to delete this quality plan? This action cannot be undone.',
    'pqp.statTotal': 'Total',
    'pqp.activeRate': 'Approved Rate',
    'pqp.qualityAssessment': 'Quality Assessment',


    // NOI
    'noi.title': 'Notice of Inspection',
    'noi.listTitle': 'NOI List',
    'noi.addNew': 'Add New NOI',
    'noi.bulkAdd': 'Bulk Add',
    'noi.batchPrint': 'Batch Print',
    'noi.package': 'Subject',
    'noi.itpNo': 'ITP no.',
    'noi.issueDate': 'Issue Date',
    'noi.inspectionDate': 'Inspection Date',
    'noi.inspectionTime': 'Inspection Time',
    'noi.eventNo': 'Event #',
    'noi.checkpoint': 'Checkpoint',
    'noi.relatedITR': 'Related ITR',
    'noi.ncrOnly': 'NCR Re-inspection Only',
    'noi.bulkAddSummary': 'Total {count} items, Reference No will be generated by system',
    'noi.bulkAddSaving': 'Adding...',
    'noi.bulkAddAction': 'Bulk Add {count} items',
    'noi.searchPlaceholder': 'Search NOI...',
    'noi.stats.open': 'Open',
    'noi.stats.closed': 'Closed',
    'noi.stats.total': 'Total',
    'noi.stats.openRate': 'Open Rate',
    'noi.tooltip.edit': 'Edit',
    'noi.tooltip.details': 'Details',
    'noi.tooltip.delete': 'Delete',
    'noi.tooltip.print': 'Please select NOIs to print first',
    'noi.tooltip.printCount': 'Print {count} items',
    'noi.tooltip.viewRelatedITR': 'View {count} related ITR',
    'noi.status.open': 'Open',
    'noi.status.closed': 'Closed',
    'noi.status.underReview': 'Under Review',
    'noi.status.reject': 'Reject',
    'noi.sectionQuality': 'Quality Assessment',
    'noi.closeoutDate': 'Close-out Date',
    'noi.ncrReference': 'NCR Reference no.',
    'noi.editTitle': 'Edit NOI',
    'noi.addTitle': 'Add NOI',
    'noi.detailsTitle': 'NOI Details',
    'noi.print.title': 'Batch Notice of Inspection (NOI)',
    'noi.print.date': 'Print Date',
    'noi.print.commonSection': 'Common Information',
    'noi.print.listTitle': 'NOI Data List',
    'noi.print.count': 'Total {count} items',
    'noi.confirmDelete': 'Are you sure you want to delete this NOI item?',

    // ITR
    'itr.title': 'Inspection and Test Report',
    'itr.listTitle': 'ITR List',
    'itr.addNew': 'Add New ITR',
    'itr.inspectionDate': 'Inspection Date',
    'itr.ncrNo': 'NCR no.',
    'itr.noiNo': 'NOI no.',
    'itr.relatedNCR': 'Related NCR',
    'itr.searchPlaceholder': 'Search ITR...',
    'itr.stats.approved': 'Approved',
    'itr.stats.reject': 'Reject',
    'itr.stats.total': 'Total',
    'itr.stats.approveRate': 'Approve Rate',
    'itr.status.approved': 'Approved',
    'itr.status.reject': 'Reject',
    'itr.status.inProgress': 'In Progress',
    'itr.tooltip.edit': 'Edit',
    'itr.tooltip.details': 'Details',
    'itr.tooltip.delete': 'Delete',
    'itr.tooltip.viewRelatedNOI': 'View related NOI',
    'itr.tooltip.viewRelatedNCR': 'View related NCR',
    'itr.editTitle': 'Edit ITR',
    'itr.addTitle': 'Add ITR',
    'itr.detailsTitle': 'ITR Details',
    'itr.sectionInfo': 'Non-conformity Info',
    'itr.sectionPersonnel': 'Personnel & Location Info',
    'itr.sectionDisposition': 'Disposition & Repair',
    'itr.sectionReinspection': 'Re-inspection Data',
    'itr.sectionQuality': 'Quality Assessment',
    'itr.closeoutDate': 'Close-out Date',
    'itr.referenceStandards': 'Reference Standards/Clauses',
    'itr.detailsDescription': 'Details/Description of Nonconformity',
    'itr.foundLocation': 'Nonconformity Found Location',
    'itr.raisedBy': 'Raised By',
    'itr.serialNumbers': "Serial No.'s/Batch Ref affected",
    'itr.reInspectionNo': 'Re-Inspection no.',
    'itr.photo.defect': 'Defect Photos',
    'itr.photo.improvement': 'Improvement Photos',
    'itr.photo.upload': 'Upload Photos',
    'itr.revCustom': 'Rev5.0 or above (Custom)',
    'itr.revCustomPlaceholder': 'e.g. Rev5.0',
    'itr.selectNOI': 'Select NOI',
    'itr.confirmDelete': 'Are you sure you want to delete this ITR item?',
    'itr.saveError': 'ITR save failed, please ensure backend is running and try again.',

    // Checklist
    'checklist.title': 'Checklist List',
    'checklist.listTitle': 'Checklist Records',
    'checklist.addNew': 'New Checklist',
    'checklist.searchPlaceholder': 'Search Checklist...',
    'checklist.recordNotFound': 'Record not found',
    'checklist.selectNoi': 'Select NOI',
    'checklist.status.ongoing': 'Ongoing',
    'checklist.status.pass': 'Pass',
    'checklist.status.fail': 'Fail',

    // NCR
    'ncr.title': 'NCR List',
    'ncr.addNew': 'Add New NCR',
    'ncr.editTitle': 'Edit NCR',
    'ncr.addTitle': 'Add NCR',
    'ncr.viewTitle': 'NCR Details',
    'ncr.type': 'Type',
    'ncr.raiseDate': 'Raise Date',
    'ncr.documentNumber': 'Reference no.',
    'ncr.itrNo': 'ITR no.',
    'ncr.refIntegrity': 'Product Integrity related',
    'ncr.refPermanentDeviation': 'Permanent Product Deviation',
    'ncr.refImpactOM': 'Impact to O&M',
    'ncr.sectionDisposition': 'Disposition & Repair',
    'ncr.repairMethod': 'Repair Method Statement',
    'ncr.correctionAction': 'Immediate Correction Action Proposal',
    'ncr.rootCause': 'Root Cause Analysis (how/why?)',
    'ncr.correctiveActions': 'Corrective Actions',
    'ncr.preventiveAction': 'Preventive Action',
    'ncr.integrityStatement': 'Final Product Integrity Statement',
    'ncr.sectionReinspection': 'Re-inspection Info',
    'ncr.noiNo': 'NOI no.',
    'ncr.noiNoPlaceholder': 'Select NOI',
    'ncr.reinspectionNo': 'Re-Inspection no.',
    'ncr.sectionQuality': 'Quality Assessment',
    'ncr.integrityRelated': 'Product Integrity related?',
    'ncr.permanentDeviation': 'Permanent Product Deviation',
    'ncr.impactOM': 'Impact to O&M?',
    'ncr.confirmDelete': 'Are you sure you want to delete this NCR item? This action cannot be undone.',
    'ncr.searchPlaceholder': 'Search NCR...',
    'ncr.type.design': 'Design',
    'ncr.type.material': 'Material',
    'ncr.type.workmanship': 'Workmanship',
    'ncr.type.document': 'Document',
    'ncr.disposition.useAsIs': 'Use As Is',
    'ncr.disposition.repair': 'Repair',
    'ncr.disposition.rework': 'Rework',
    'ncr.disposition.reject': 'Reject',


    // OBS
    'obs.title': 'OBS List',
    'obs.listTitle': 'OBS List',
    'obs.addNew': 'Add New OBS',
    'obs.editTitle': 'Edit OBS',
    'obs.addTitle': 'Add OBS',
    'obs.viewTitle': 'OBS Details',
    'obs.allStatus': 'All Status',
    'obs.allContractors': 'All Contractors',
    'obs.startDatePlaceholder': 'Start Date',
    'obs.endDatePlaceholder': 'End Date',
    'obs.searchPlaceholder': 'Search OBS...',
    'obs.statsTitle': 'Status Statistics',
    'obs.statOpen': 'Open',
    'obs.statClosed': 'Closed',
    'obs.statTotal': 'Total',
    'obs.statOpenRate': 'Open Rate',
    'obs.sectionInfo': 'Non-conformity Info',
    'obs.sectionPersonnelLocation': 'Personnel & Location Info',
    'obs.refNo': 'Reference no.',
    'obs.refNoHint': '(Generated by system)',
    'obs.subject': 'Subject',
    'obs.status': 'Status',
    'obs.raiseDate': 'Raise Date',
    'obs.closeoutDate': 'Close-out Date',
    'obs.type': 'Type',
    'obs.typePlaceholder': 'Select Type',
    'obs.contractor': 'Contractor',
    'obs.contractorPlaceholder': 'Select Contractor',
    'obs.refStandards': 'Reference Standards/Clauses',
    'obs.detailsDescription': 'Details/Description of Nonconformity',
    'obs.foundLocation': 'Nonconformity Found Location',
    'obs.defectPhotos': 'Defect Photos',
    'obs.improvementPhotos': 'Improvement Photos',
    'obs.uploadPhotos': '+ Upload Photos',
    'obs.attachments': 'Attachments',
    'obs.uploadFiles': '+ Upload Files',
    'obs.foundBy': 'Found By',
    'obs.raisedBy': 'Raised By',
    'obs.serialNumbers': "Serial No.'s/Batch Ref affected",
    'obs.productDisposition': 'Product Disposition',
    'obs.productDispositionPlaceholder': 'Select Disposition',
    'obs.confirmDelete': 'Are you sure you want to delete this OBS item?',

    // FAT
    'fat.title': 'Factory Acceptance Test',
    'fat.listTitle': 'FAT List',
    'fat.statsTitle': 'Status Statistics',
    'fat.addNew': 'Add FAT',
    'fat.searchPlaceholder': 'Search FAT...',
    'fat.stats.total': 'Total',
    'fat.stats.withDetails': 'With Details',
    'fat.stats.detailsRate': 'Details Rate %',
    'fat.equipment': 'Equipment',
    'fat.supplier': 'Supplier',
    'fat.procedure': 'Procedure',
    'fat.location': 'Location',
    'fat.startDate': 'Start Date',
    'fat.endDate': 'End Date',
    'fat.deliveryFrom': 'Delivery From',
    'fat.deliveryTo': 'Delivery To',
    'fat.siteReadiness': 'Site Readiness',
    'fat.moveInDate': 'Move-in Date',
    'fat.editTitle': 'Edit FAT',
    'fat.addTitle': 'Add FAT',
    'fat.detailsTitle': 'FAT Details',
    'fat.detailModalTitle': 'FAT Detail',
    'fat.sectionInfo': 'FAT Info',
    'fat.sectionBaseInfo': 'FAT Base Info',
    'fat.sectionDetails': 'FAT Detail Items',
    'fat.colSNo': 'S.No.',
    'fat.colItemName': 'Item Name',
    'fat.colSpecification': 'Specification',
    'fat.colQty': 'Qty',
    'fat.colUnit': 'Unit',
    'fat.colAcceptanceCriteria': 'Acceptance Criteria',
    'fat.colActualValue': 'FAT Actual Measured Value',
    'fat.colJudgment': 'FAT Judgment',
    'fat.colRemarks': 'Remarks',
    'fat.colOperation': 'Operation',
    'fat.addRow': 'Add Row',
    'fat.tooltip.edit': 'Edit',
    'fat.tooltip.details': 'Details',
    'fat.tooltip.addDetails': 'Add Details',
    'fat.tooltip.delete': 'Delete',
    'fat.confirmDelete': 'Are you sure you want to delete this FAT item?',

    // Audit
    'audit.title': 'Audit',
    'audit.listTitle': 'Audit List',
    'audit.addNew': 'Add Audit',
    'audit.report': 'Audit Report',
    'audit.searchPlaceholder': 'Search Audit...',
    'audit.auditNo': 'Audit No.',
    'audit.auditTitle': 'Subject',
    'audit.date': 'Date',
    'audit.location': 'Location',
    'audit.auditor': 'Auditor',
    'audit.findings': 'Findings/Remarks',
    'audit.editTitle': 'Edit Audit',
    'audit.addTitle': 'New Audit',
    'audit.confirmDelete': 'Are you sure you want to delete this audit?',
    'audit.sectionQuality': 'Quality Assessment',

    // Owner Performance
    'ownerPerformance.title': 'Owner Performance',
    'ownerPerformance.placeholder': 'Owner Performance tracking and analytics content will be implemented here.',

    // File Upload
    'fileUpload.dropHere': 'Drop files here or click to upload',
    'fileUpload.fileTooLarge': 'File is too large',
    'fileUpload.maxFiles': 'Maximum files',
    'fileUpload.maxSize': 'Maximum size',
    'fileUpload.tooManyFiles': 'Too many files',

    // Naming Rules
    'namingRules.title': 'Document Naming Rules',
    'namingRules.subtitle': 'Configure document naming conventions',
    'namingRules.hint': 'Hint',
    'namingRules.hintContent': 'Configure naming patterns for different document types',
    'namingRules.save': 'Save',
    'namingRules.saved': 'Saved successfully',

    // OSD
    'osd.title': 'OSD Document',
    'osd.description': 'Overage Shortage Damage Management',
    'osd.placeholderTitle': 'OSD Title',

    // Self Inspection
    'selfInspection.title': 'Self Inspection',

    // Contractors
    'contractors.title': 'Contractors',
    'contractors.serialNumber': 'No.',
    'contractors.addContractor': 'Add Contractor',
    'contractors.editContractor': 'Edit Contractor',
    'contractors.package': 'Package',
    'contractors.abbreviation': 'Vendor Code',
    'contractors.name': 'Contractor',
    'contractors.scope': 'Scope',
    'contractors.contactPerson': 'Contact Person',
    'contractors.contact': 'Contact Person',
    'contractors.email': 'Email',
    'contractors.phone': 'Phone',
    'contractors.address': 'Address',
    'contractors.status': 'Status',
    'contractors.operations': 'Operations',
    'contractors.confirmDelete': 'Are you sure you want to delete this contractor?',
    'contractors.status.active': 'Active',
    'contractors.status.inactive': 'Inactive',

    // Status values
    'status.approved': 'Approved',
    'status.reject': 'Reject',
    'status.underReview': 'Under Review',
    'status.notSubmit': 'Not Submit',
    'status.open': 'Open',
    'status.closed': 'Closed',
    'status.void': 'Void',

    // Form
    'form.requiredHint': 'Fields marked with * are required',
    'form.autoGenerated': 'Auto Generated',
    'form.source': 'Source',

    // FollowUp
    'followup.title': 'Follow Up Issues',
    'followup.listTitle': 'Issue List',
    'followup.addNew': 'Add New Issue',
    'followup.statsTitle': 'Status Statistics',
    'followup.editTitle': 'Edit Issue',
    'followup.addTitle': 'Add Issue',
    'followup.detailsTitle': 'Issue Details',
    'followup.issueNo': 'Reference no.',
    'followup.status': 'Status',
    'followup.assignedTo': 'Assigned To',
    'followup.vendor': 'Vendor / Contractor',
    'followup.sourceModule': 'Source Module',
    'followup.sourceRef': 'Source Reference No',
    'followup.createdDate': 'Created Date',
    'followup.dueDate': 'Due Date',
    'followup.description': 'Description',
    'followup.action': 'Action',
    'followup.source': 'Source',
    'followup.tooltip.goToModule': 'Go to {module}',

    // KPI
    'kpi.title': 'Key Performance Indicators (KPI)',
    'kpi.subtitle': 'KPI is based on monthly PQP, ITP, OBS, and NCR closure rates. Each indicator has a weight.',
    'kpi.weights': 'Weights',
    'kpi.trendTitle': 'KPI Trend',
    'kpi.noData': 'No monthly data yet. PQP / ITP / OBS / NCR records with dates will appear here.',
    'kpi.tableTitle': 'KPI by Contractor',
    'kpi.month': 'Month',
    'kpi.scope': 'Scope',
    'kpi.lastMonth': 'Last Month',
    'kpi.thisMonth': 'This Month',
    'kpi.trend': 'Trend',
    'kpi.variance': 'Variance',

    // KM
    'km.title': 'Knowledge Management (KM)',
    'km.systemTitle': 'Knowledge Management System',
    'km.description': 'This module manages organizational knowledge assets, documents, best practices, and experience sharing.',

    // IAM
    'iam.title': 'Identity and Access Management (IAM)',
    'iam.users': 'User Management',
    'iam.roles': 'Role Management',
    'iam.permissions': 'Permissions Preview',
    'iam.permissionStats': 'Permission Statistics',
    'iam.countPermissions': '{count} permissions',
    'iam.searchUser': 'Search users...',
    'iam.searchRole': 'Search roles...',
    'iam.userList': 'User List',
    'iam.roleList': 'Role List',
    'iam.addUser': 'Add User',
    'iam.addRole': 'Add Role',
    'iam.editUser': 'Edit User',
    'iam.editRole': 'Edit Role',
    'iam.name': 'Name',
    'iam.email': 'Email',
    'iam.role': 'Role',
    'iam.status': 'Status',
    'iam.description': 'Description',
    'iam.permissionsLabel': 'Permissions',
    'iam.placeholder.name': 'Enter name',
    'iam.placeholder.email': 'Enter email',
    'iam.placeholder.roleName': 'Enter role name',
    'iam.placeholder.roleDesc': 'Enter role description',
    'iam.status.active': 'Active',
    'iam.status.inactive': 'Inactive',
    'iam.perm.read': 'Read',
    'iam.perm.write': 'Write',
    'iam.perm.delete': 'Delete',
    'iam.perm.manageUsers': 'Manage Users',
    'iam.perm.manageRoles': 'Manage Roles',
    'iam.permDesc.read': 'Allow reading data',
    'iam.permDesc.write': 'Allow creating and modifying data',
    'iam.permDesc.delete': 'Allow deleting data',
    'iam.permDesc.manageUsers': 'Allow managing user accounts',
    'iam.permDesc.manageRoles': 'Allow managing roles and permissions',
    'iam.password': 'Password',
    'iam.confirmPassword': 'Confirm Password',
    'iam.resetPassword': 'Reset Password',
    'iam.createdDate': 'Created Date',
    'iam.deleteError': 'Failed to delete',
    'iam.fetchError': 'Failed to fetch IAM data',
    'iam.passwordMismatch': 'Passwords do not match',
    'iam.passwordTooShort': 'Password is too short',
    'iam.permissionsDesc': 'Permissions Description',
    'iam.placeholder.confirmPassword': 'Confirm password',
    'iam.placeholder.password': 'Enter password',
    'iam.roleName': 'Role Name',
    'iam.saveRoleError': 'Failed to save role',
    'iam.saveUserError': 'Failed to save user',

    // ITP
    'itp.title': 'ITP List',
    'itp.statsTitle': 'Status Statistics',
    'itp.maturitySubmission': 'Submission Maturity %',
    'itp.maturityApproval': 'Approval Maturity %',
    'itp.addNew': '+ Add ITP',
    'itp.searchPlaceholder': 'Search ITP...',
    'itp.referenceNo': 'Reference no.',
    'itp.status': 'Status',
    'itp.vendor': 'Contractor',
    'itp.description': 'Subject',
    'itp.rev': 'Version',
    'itp.submissionDate': 'Updated Date',
    'itp.editTitle': 'Edit ITP',
    'itp.addTitle': 'Add ITP',
    'itp.infoSection': 'ITP Information',
    'itp.selectContractor': 'Select Contractor',
    'itp.revPlaceholder': 'Enter Rev5.0 or higher',
    'itp.revSelectCustom': 'Rev5.0 or higher (Manual)',
    'itp.confirmDelete': 'Are you sure you want to delete this ITP item? This action cannot be undone.',
    'itp.addError': 'Failed to add. Please try again later.',
    'itp.updateError': 'Failed to update. Please try again later.',
    'itp.deleteError': 'Failed to delete. Please try again later.',
    'itp.status.approved': 'Approved',
    'itp.status.approvedWithComments': 'Approved with comments',
    'itp.status.pending': 'Pending',
    'itp.status.noSubmit': 'No submit',
    'itp.status.reviseResubmit': 'Revise & Resubmit',
    'itp.status.rejected': 'Rejected',
    'itp.status.void': 'Void',
    'itp.tooltip.edit': 'Edit',
    'itp.tooltip.details': 'Details',
    'itp.tooltip.review': 'Review ITP',
    'itp.tooltip.delete': 'Delete',
    'itp.tooltip.viewRelatedNOI': 'View {count} related NOI',
    'itp.tooltip.noRelatedNOI': 'No related NOI',
    'itp.stats.submission': 'Submission',
    'itp.stats.submissionMaturity': 'Submission Maturity %',
    'itp.stats.approvalMaturity': 'Approval Maturity %',

    'itp.detail.title': 'ITP Detail',
    'itp.detail.beforeConstruction': 'A. Before Construction',
    'itp.detail.duringConstruction': 'B. During Construction',
    'itp.detail.afterConstruction': 'C. After Construction',
    'itp.detail.eventNo': 'Event No.',
    'itp.detail.activity': 'Activity',
    'itp.detail.standard': 'Standard/Code or Guidelines',
    'itp.detail.acceptanceCriteria': 'Acceptance Criteria',
    'itp.detail.checkTiming': 'Check Timing',
    'itp.detail.inspectionMethod': 'Inspection Method',
    'itp.detail.frequency': 'Frequency',
    'itp.detail.nonconformity': 'Nonconformity Treatment',
    'itp.detail.records': 'Records',
    'itp.detail.verificationPoint': 'Verification Point',
    'itp.detail.subcon': 'Subcon',
    'itp.detail.epci': 'EPCI',
    'itp.detail.employer': 'Employer',
    'itp.detail.hse': 'HSE',

    'itp.selfInspection.title': 'Reinforcing Steel Material Self-Inspection Checklist',
    'itp.selfInspection.organizingUnit': 'Organizing Unit',
    'itp.selfInspection.supervisingUnit': 'Supervising Unit',
    'itp.selfInspection.contractor': 'Contractor',
    'itp.selfInspection.location': 'Construction Location',
    'itp.selfInspection.applicationDate': 'Application Date',
    'itp.selfInspection.entryType': 'Entry Type',
    'itp.selfInspection.entrySequence': 'Entry Seq No.',
    'itp.selfInspection.datePlaceholder': 'YYYY MM DD',
    'itp.selfInspection.contractQty': 'Contract Qty (ton)',
    'itp.selfInspection.previous': 'Previous (ton)',
    'itp.selfInspection.current': 'Current (ton)',
    'itp.selfInspection.accumulated': 'Accumulated (ton)',
    'itp.selfInspection.item': 'Inspection Item',
    'itp.selfInspection.brand': 'Brand',
    'itp.selfInspection.heatNo': 'Heat No',
    'itp.selfInspection.model': 'Model',
    'itp.selfInspection.number': '# (Size)',
    'itp.selfInspection.subtotal': 'Subtotal (ton)',
    'itp.selfInspection.sampleQty': 'Sample Qty',
    'itp.selfInspection.total': 'Total',
    'itp.selfInspection.attachments': 'Attachments',
    'itp.selfInspection.attach.spec': 'Spec',
    'itp.selfInspection.attach.submission': 'Submission',
    'itp.selfInspection.attach.drawing': 'Drawing',
    'itp.selfInspection.attach.other': 'Other (QC Cert, Non-radioactive)',
    'itp.selfInspection.q.no': 'No.',
    'itp.selfInspection.q.item': 'Inspection Item',
    'itp.selfInspection.q1': 'Whether the brand and model of the equipment/material comply with regulations',
    'itp.selfInspection.q2': 'The quantity of this entry is: SD280W【 】tons; SD420W【 】tons',
    'itp.selfInspection.q3': 'Whether the specification and size of the equipment/material comply with regulations',
    'itp.selfInspection.q4': 'Whether the color and accessories are complete and meet the requirements',
    'itp.selfInspection.q5': 'Whether the appearance is free of improper damage',
    'itp.selfInspection.q6': 'Whether the storage location and preservation method meet the requirements',
    'itp.selfInspection.q7': 'Whether the attached data is complete',
    'itp.selfInspection.q7.customs': 'Customs Import Proof',
    'itp.selfInspection.q7.materialCert': 'Mill & Material Cert',
    'itp.selfInspection.q7.testReport': 'Mill Test Report',
    'itp.selfInspection.q7.equipmentList': 'Equipment List',
    'itp.selfInspection.q7.other': 'Other',
    'itp.selfInspection.auditResult': 'Audit Result',
    'itp.selfInspection.audit.approved': 'Approved',
    'itp.selfInspection.audit.resample': 'Resample',
    'itp.selfInspection.audit.reject': 'Reject',
    'itp.selfInspection.sd280': 'SD280W (Deformed Bar #3)',
    'itp.selfInspection.sd420': 'SD420W (High-Yield Bar #4~#8)',
    'itp.selfInspection.siteSupervisor': 'Site Supervisor',
    'itp.selfInspection.fieldEngineer': 'Field Engineer',
    'itp.selfInspection.inspectionLocation': 'Inspection Location',
    'itp.selfInspection.attachedInfo': 'Attached Info',
    'itp.selfInspection.deformedBar': 'Deformed Bar',
    'itp.selfInspection.coupler': 'Coupler',
    'itp.selfInspection.attachment.spec': 'Spec',
    'itp.selfInspection.attachment.submission': 'Submission',
    'itp.selfInspection.attachment.drawing': 'Drawing',
    'itp.selfInspection.attachment.other': 'Other (QC Cert, Non-radioactive)',
    'itp.selfInspection.attachment.customs': 'Customs Import Proof',
    'itp.selfInspection.attachment.materialCert': 'Mill & Material Cert',
    'itp.selfInspection.attachment.testReport': 'Mill Test Report',
    'itp.selfInspection.attachment.equipmentList': 'Equipment List',
    'itp.selfInspection.questionNo': 'No.',
    'itp.detail.saveSuccess': 'ITP data saved successfully.',
    'itp.detail.saveError': 'Save failed: ',
    'itp.detail.saveErrorGeneric': 'Save failed, please try again later.',
    'itp.detail.missingId': 'Cannot save: Missing ITP ID',
    'itp.detail.nonconformityTreatment': 'Nonconformity Treatment',
    'itp.selfInspection.auditComment': 'Audit Comment',
    'itp.selfInspection.inspectionItem': 'Inspection Item',
    'itp.selfInspection.na': 'N/A',
    'approved': 'Approved',
    'reject': 'Reject',
    'resample': 'Resample',
    'common.total': 'Total',
  },

  zh: {
    // Login
    'login.welcome': '歡迎回來',
    'login.subtitle': '輸入您的憑證以登入 Qualitas',
    'login.email': '電子郵件地址',
    'login.password': '密碼',
    'login.signIn': '登入',
    'login.signingIn': '登入中...',
    'login.failed': '登入失敗。請檢查您的憑證。',

    // Common
    'common.edit': '編輯',
    'common.details': '詳情',
    'common.delete': '刪除',
    'common.save': '儲存',
    'common.saving': '儲存中...',
    'common.saveFailed': '儲存失敗',
    'common.cancel': '取消',
    'common.add': '新增',
    'common.addDate': '插入日期',
    'common.search': '搜尋',
    'common.filter': '篩選',
    'common.all': '全部',
    'common.loading': '載入中...',
    'common.retry': '重試',
    'common.confirmDeleteTitle': '確認刪除',
    'common.operations': '操作',
    'common.noData': '沒有符合條件的資料',
    'common.confirmDelete': '您確定要刪除此項目嗎？',
    'common.yes': '是',
    'common.no': '否',
    'common.status': '狀態',
    'common.vendor': '廠商',
    'common.contractor': '承包商',
    'common.title': '標題',
    'common.referenceNo': '參考編號',
    'common.version': '版本',
    'common.date': '日期',
    'common.updatedDate': '更新日期',
    'common.createdDate': '建立日期',
    'common.remark': '備註',
    'common.description': '描述',
    'common.viewDetails': '查看詳情 →',
    'common.close': '關閉',
    'common.print': '列印',
    'common.selectPlaceholder': '選擇',
    'common.tbc': '待確認',
    'common.na': '不適用',
    'common.today': '今天',
    'common.contactInfo': '聯絡資訊',
    'common.baseInfo': '基本資訊',
    'common.back': '返回',
    'common.selectContractor': '請選擇承包商',
    'common.selectDate': '請選擇日期',
    'common.fillAtLeastOne': '請至少填寫一筆資料',
    'common.invalidStatusTransition': '此狀態轉換不被允許',
    'common.attachments': '附件',
    'common.uploadFiles': '+ 上傳檔案',
    'common.allContractors': '全部承包商',
    'common.batchDelete': '批量刪除',
    'common.changeStatus': '變更狀態',
    'common.clearSelection': '清除選擇',
    'common.confirmDeleteMsg': '您確定要刪除此項目嗎？',
    'common.dueDate': '到期日',
    'common.exportExcel': '匯出 Excel',
    'common.items': '項',
    'common.noDataToExport': '無資料可匯出',
    'common.notGenerated': '未產生',
    'common.selected': '已選擇',
    'common.status.open': '開啟',
    'common.statistics': '統計數據',
    'common.passRate': '合格率',
    'common.activity': '施工作業',
    'common.package': '分包項目',

    // Form
    'form.requiredHint': '打*的欄位為必填',
    'form.autoGenerated': '系統自動帶入',
    'form.source': '來源',

    // Home
    'home.welcome': '歡迎',
    'home.adminUser': '管理員',
    'home.logout': '登出',
    'home.dashboard.description': '數據儀表板與統計分析',
    'home.kpi.description': '關鍵績效指標管理',
    'home.followup.description': '後續問題追蹤管理',
    'home.pqp.description': '品質計劃管理',
    'home.itp.description': '檢驗與測試計劃管理',
    'home.checklist.description': '品質查驗紀錄與表格管理',
    'home.noi.description': '檢驗通知管理',
    'home.itr.description': '檢驗與測試報告',
    'home.osd.description': '溢短損管理',
    'home.obs.description': '觀察記錄管理',
    'home.ncr.description': '不符合報告管理',
    'home.fat.description': '工廠驗收測試',
    // Audit
    'home.audit.description': '稽核', // Keep existing description key for Home
    'home.km.description': '知識管理系統',
    'home.ownerPerformance.description': '業主績效追蹤與分析',
    'home.iam.description': '管理使用者、角色和權限設定',

    // Dashboard
    'dashboard.title': '儀表板',
    'dashboard.pqpMaturity': 'PQP 成熟度',
    'dashboard.qualityPlan': '品質計劃',
    'dashboard.completion': '完成度',
    'dashboard.itpTotal': 'ITP 總數',
    'dashboard.submitted': '已提交',
    'dashboard.approved': '已批准',
    'dashboard.obsTotal': 'OBS 總數',
    'dashboard.open': '開啟',
    'dashboard.closed': '已關閉',
    'dashboard.ncrTotal': 'NCR 總數',
    'dashboard.noiTotal': 'NOI 總數',
    'dashboard.itrTotal': 'ITR 總數',
    'dashboard.pqpMaturityAnalysis': 'PQP 成熟度分析',
    'dashboard.itpMaturityAnalysis': 'ITP 成熟度分析',
    'dashboard.obsStatusAnalysis': 'OBS 狀態分析',
    'dashboard.ncrVendorAnalysis': 'NCR 廠商分析',
    'dashboard.ncrStatusAnalysis': 'NCR 狀態分析',
    'dashboard.kpiOverview': '關鍵指標總覽',
    'dashboard.subtitle': '數據總覽與分析',
    'dashboard.interactiveCharts': '互動式圖表',
    'dashboard.ncrStatusChart': 'NCR 狀態圖表',
    'dashboard.noiCount': 'NOI 計數',
    'dashboard.noiTrendChart': 'NOI 趨勢圖表',
    'dashboard.upcomingTasks': '即將到期的任務',

    // PQP
    'pqp.title': '品質計劃列表',
    'pqp.addNew': '新增品質計劃',
    'pqp.statusStats': '狀態統計',
    'pqp.total': '總數',
    'pqp.approvedRate': '批准率',
    'pqp.referenceNo': '參考編號',
    'pqp.contractor': '承包商',
    'pqp.version': '版本',
    'pqp.updatedDate': '更新日期',
    'pqp.allContractors': '全部承包商',
    'pqp.allStatus': '全部狀態',
    'pqp.startDate': '開始日期',
    'pqp.endDate': '結束日期',
    'pqp.subject': '主旨',
    'pqp.titleShort': 'PQP',
    'pqp.searchPlaceholder': '搜尋 PQP...',
    'pqp.createdDate': '建立日期',
    'pqp.status.approved': '已核准',
    'pqp.status.reject': '退件',
    'pqp.status.notSubmit': '未提交',
    'pqp.status.underReview': '審核中',
    'pqp.editTitle': '編輯 PQP',
    'pqp.addTitle': '新增 PQP',
    'pqp.infoSection': '品質計劃資訊',
    'pqp.refNoHint': '(由系統自動產生)',
    'pqp.revPlaceholder': '請輸入 Rev5.0 以上版本，例如 Rev5.0',
    'pqp.revFormatError': '請輸入格式如 Rev5.0、Rev6.0',
    'pqp.revMinError': '自訂版本必須為 Rev5.0 以上',
    'pqp.revSelectCustom': 'Rev5.0 以上（手動輸入）',
    'pqp.saveError': '儲存失敗，請稍後再試',
    'pqp.saving': '儲存中...',
    'pqp.titleRequired': '請輸入主旨',
    'pqp.vendorRequired': '請選擇承包商',
    'pqp.versionRequired': '請提供版本',
    'pqp.remark': '備註',
    'pqp.addDate': '加入日期',
    'pqp.detail.title': 'PQP 詳情',
    'pqp.tooltip.edit': '編輯',
    'pqp.tooltip.details': '查看詳情',
    'pqp.tooltip.delete': '刪除',
    'pqp.reviewITP': '審核 ITP',
    'pqp.relatedNOI': '相關 NOI',
    'pqp.confirmDeleteMessage': '確定要刪除此品質計劃嗎？此操作無法復原。',
    'pqp.statTotal': '總數',
    'pqp.activeRate': '合格率',
    'pqp.qualityAssessment': '品質評估',


    // NOI
    'noi.title': '檢驗通知',
    'noi.listTitle': 'NOI 列表',
    'noi.addNew': '新增 NOI',
    'noi.bulkAdd': '批次新增',
    'noi.batchPrint': '批次列印',
    'noi.package': '主旨',
    'noi.itpNo': 'ITP 編號',
    'noi.issueDate': '發佈日期',
    'noi.inspectionDate': '檢驗日期',
    'noi.inspectionTime': '檢驗時間',
    'noi.eventNo': '事件編號',
    'noi.checkpoint': '檢查點',
    'noi.relatedITR': '相關 ITR',
    'noi.ncrOnly': '僅 NCR 重新檢驗',
    'noi.bulkAddSummary': '共 {count} 筆資料，Reference No 將由系統自動產生',
    'noi.bulkAddSaving': '新增中...',
    'noi.bulkAddAction': '批次新增 {count} 筆',
    'noi.searchPlaceholder': '搜尋 NOI...',
    'noi.stats.open': '開啟',
    'noi.stats.closed': '已關閉',
    'noi.stats.total': '總數',
    'noi.stats.openRate': '開啟率',
    'noi.tooltip.edit': '編輯',
    'noi.tooltip.details': '查看詳情',
    'noi.tooltip.delete': '刪除',
    'noi.tooltip.print': '請先勾選要列印的 NOI',
    'noi.tooltip.printCount': '列印 {count} 筆',
    'noi.tooltip.viewRelatedITR': '查看 {count} 個相關 ITR',
    'noi.status.open': '開啟',
    'noi.status.closed': '已關閉',
    'noi.status.underReview': '審核中',
    'noi.status.reject': '駁回',
    'noi.sectionQuality': '品質評估',
    'noi.closeoutDate': '結案日期',
    'noi.ncrReference': 'NCR 參考編號',
    'noi.editTitle': '編輯 NOI',
    'noi.addTitle': '新增 NOI',
    'noi.detailsTitle': 'NOI 詳情',
    'noi.print.title': '批次檢驗通知 (NOI)',
    'noi.print.date': '列印日期',
    'noi.print.commonSection': '共同資訊',
    'noi.print.listTitle': '各筆 NOI 資料',
    'noi.print.count': '共 {count} 筆',
    'noi.confirmDelete': '確定要刪除此 NOI 項目嗎？',

    // ITR
    'itr.title': '檢驗與測試報告',
    'itr.listTitle': 'ITR 列表',
    'itr.addNew': '新增 ITR',
    'itr.inspectionDate': '檢驗日期',
    'itr.ncrNo': 'NCR 編號',
    'itr.noiNo': 'NOI 編號',
    'itr.relatedNCR': '相關 NCR',
    'itr.searchPlaceholder': '搜尋 ITR...',
    'itr.stats.approved': '已核准',
    'itr.stats.reject': '駁回',
    'itr.stats.total': '總數',
    'itr.stats.approveRate': '核准率',
    'itr.status.approved': '已核准',
    'itr.status.reject': '駁回',
    'itr.status.inProgress': '進行中',
    'itr.tooltip.edit': '編輯',
    'itr.tooltip.details': '查看詳情',
    'itr.tooltip.delete': '刪除',
    'itr.tooltip.viewRelatedNOI': '查看相關 NOI',
    'itr.tooltip.viewRelatedNCR': '查看相關 NCR',
    'itr.editTitle': '編輯 ITR',
    'itr.addTitle': '新增 ITR',
    'itr.detailsTitle': 'ITR 詳情',
    'itr.sectionInfo': '不符合項目資訊',
    'itr.sectionPersonnel': '人員與位置資訊',
    'itr.sectionDisposition': '處置與修復',
    'itr.sectionReinspection': '複檢資料',
    'itr.sectionQuality': '品質評估',
    'itr.closeoutDate': '結案日期',
    'itr.referenceStandards': '參考標準/條款',
    'itr.detailsDescription': '不符合項目詳情/說明',
    'itr.foundLocation': '不符合項目發現位置',
    'itr.raisedBy': '提出人',
    'itr.serialNumbers': '受影響序號/批次參考',
    'itr.reInspectionNo': '複檢編號',
    'itr.photo.defect': '缺失照片',
    'itr.photo.improvement': '改善照片',
    'itr.photo.upload': '上傳照片',
    'itr.revCustom': 'Rev5.0 以上（手動輸入）',
    'itr.revCustomPlaceholder': '請輸入 Rev5.0 以上版本，例如 Rev5.0',
    'itr.selectNOI': '選擇 NOI',
    'itr.confirmDelete': '確定要刪除此 ITR 項目嗎？',
    'itr.saveError': 'ITR 儲存失敗，請確認後端已啟動並稍後再試。',

    // NCR
    'ncr.title': 'NCR 列表',
    'ncr.addNew': '新增 NCR',
    'ncr.editTitle': '編輯 NCR',
    'ncr.addTitle': '新增 NCR',
    'ncr.viewTitle': 'NCR 詳情',
    'ncr.type': '類型',
    'ncr.raiseDate': '提出日期',
    'ncr.documentNumber': '參考編號',
    'ncr.itrNo': 'ITR 編號',
    'ncr.refIntegrity': '產品完整性相關',
    'ncr.refPermanentDeviation': '永久產品偏差',
    'ncr.refImpactOM': '對運維的影響',
    'ncr.sectionDisposition': '處置與修復',
    'ncr.repairMethod': '修復方案說明',
    'ncr.correctionAction': '立即糾正措施建議',
    'ncr.rootCause': '根本原因分析 (如何/為何？)',
    'ncr.correctiveActions': '糾正措施',
    'ncr.preventiveAction': '預防措施',
    'ncr.integrityStatement': '最終產品完整性聲明',
    'ncr.sectionReinspection': '複檢資料',
    'ncr.noiNo': 'NOI 編號',
    'ncr.noiNoPlaceholder': '選擇 NOI',
    'ncr.reinspectionNo': '複檢編號',
    'ncr.sectionQuality': '品質評估',
    'ncr.integrityRelated': '是否與產品完整性相關？',
    'ncr.permanentDeviation': '永久產品偏差',
    'ncr.impactOM': '對運維是否有影響？',
    'ncr.confirmDelete': '確定要刪除此 NCR 項目嗎？此操作無法復原。',
    'ncr.searchPlaceholder': '搜尋 NCR...',
    'ncr.type.design': '設計',
    'ncr.type.material': '材料',
    'ncr.type.workmanship': '工藝',
    'ncr.type.document': '文件',
    'ncr.disposition.useAsIs': '照現狀使用',
    'ncr.disposition.repair': '修復',
    'ncr.disposition.rework': '返工',
    'ncr.disposition.reject': '退件',

    // OBS
    'obs.title': 'OBS 列表',
    'obs.listTitle': 'OBS 列表',
    'obs.addNew': '新增 OBS',
    'obs.editTitle': '編輯 OBS',
    'obs.addTitle': '新增 OBS',
    'obs.viewTitle': 'OBS 詳情',
    'obs.allStatus': '全部狀態',
    'obs.allContractors': '全部承包商',
    'obs.startDatePlaceholder': '開始日期',
    'obs.endDatePlaceholder': '結束日期',
    'obs.searchPlaceholder': '搜尋 OBS...',
    'obs.statsTitle': '狀態統計',
    'obs.statOpen': '開啟',
    'obs.statClosed': '已關閉',
    'obs.statTotal': '總量',
    'obs.statOpenRate': '開啟率',
    'obs.sectionInfo': '不符合項目資訊',
    'obs.sectionPersonnelLocation': '人員與位置資訊',
    'obs.refNo': '參考編號',
    'obs.refNoHint': '(由系統自動產生)',
    'obs.subject': '主旨',
    'obs.status': '狀態',
    'obs.raiseDate': '提出日期',
    'obs.closeoutDate': '關閉日期',
    'obs.type': '類型',
    'obs.typePlaceholder': '選擇類型',
    'obs.contractor': '承包商',
    'obs.contractorPlaceholder': '選擇承包商',
    'obs.refStandards': '參考標準/條款',
    'obs.detailsDescription': '不符合項詳情/描述',
    'obs.foundLocation': '發現不符合項位置',
    'obs.defectPhotos': '缺陷照片',
    'obs.improvementPhotos': '改進照片',
    'obs.uploadPhotos': '+ 上傳照片',
    'obs.attachments': '附件',
    'obs.uploadFiles': '+ 上傳檔案',
    'obs.foundBy': '發現人',
    'obs.raisedBy': '提出人',
    'obs.serialNumbers': '受影響的序號/批次參考',
    'obs.productDisposition': '產品處置',
    'obs.productDispositionPlaceholder': '選擇處置',
    'obs.confirmDelete': '確定要刪除此 OBS 項目嗎？',

    // FAT
    'fat.title': '工廠驗收測試',
    'fat.listTitle': 'FAT 列表',
    'fat.statsTitle': '狀態統計',
    'fat.addNew': '新增 FAT',
    'fat.searchPlaceholder': '搜尋 FAT...',
    'fat.stats.total': '總數',
    'fat.stats.withDetails': '包含詳情',
    'fat.stats.detailsRate': '詳情比例 %',
    'fat.equipment': '設備名稱',
    'fat.supplier': '供應商',
    'fat.procedure': '測試程序',
    'fat.location': '地點',
    'fat.startDate': '開始日期',
    'fat.endDate': '結束日期',
    'fat.deliveryFrom': '出貨地',
    'fat.deliveryTo': '目的地',
    'fat.siteReadiness': '工地就緒狀況',
    'fat.moveInDate': '進場日期',
    'fat.editTitle': '編輯 FAT',
    'fat.addTitle': '新增 FAT',
    'fat.detailsTitle': 'FAT 詳情',
    'fat.detailModalTitle': 'FAT 詳細項目',
    'fat.sectionInfo': 'FAT 資訊',
    'fat.sectionBaseInfo': 'FAT 基本資訊',
    'fat.sectionDetails': 'FAT 詳細項目',
    'fat.colSNo': '序號',
    'fat.colItemName': '項目名稱',
    'fat.colSpecification': '規格',
    'fat.colQty': '數量',
    'fat.colUnit': '單位',
    'fat.colAcceptanceCriteria': '合格判定標準',
    'fat.colActualValue': 'FAT 實際量測值',
    'fat.colJudgment': 'FAT 判定',
    'fat.colRemarks': '備註',
    'fat.colOperation': '操作',
    'fat.addRow': '新增行',
    'fat.tooltip.edit': '編輯',
    'fat.tooltip.details': '查看詳情',
    'fat.tooltip.addDetails': '新增詳情',
    'fat.tooltip.delete': '刪除',
    'fat.confirmDelete': '確定要刪除此 FAT 項目嗎？',

    // Audit
    'audit.title': '稽核',
    'audit.listTitle': '稽核列表',
    'audit.addNew': '新增稽核',
    'audit.report': '稽核報告',
    'audit.searchPlaceholder': '搜尋稽核...',
    'audit.auditNo': '稽核編號',
    'audit.auditTitle': '主旨',
    'audit.date': '日期',
    'audit.location': '地點',
    'audit.auditor': '稽核員', // Correcting logic
    'audit.findings': '發現/備註',
    'audit.editTitle': '編輯稽核',
    'audit.addTitle': '新增稽核',
    'audit.confirmDelete': '您確定要刪除此稽核嗎？',
    'audit.sectionQuality': '品質評估',

    // Owner Performance
    'ownerPerformance.title': '業主績效',
    'ownerPerformance.placeholder': '業主績效追蹤與分析內容將在此實作。',

    // Contractors
    'contractors.title': '承包商列表',
    'contractors.serialNumber': '序號',
    'contractors.addContractor': '新增承包商',
    'contractors.editContractor': '編輯承包商',
    'contractors.package': 'Package',
    'contractors.abbreviation': '廠商代號',
    'contractors.name': '承包商名稱',
    'contractors.scope': '工作範圍',
    'contractors.contactPerson': '聯絡人',
    'contractors.contact': '聯絡人',
    'contractors.email': '電子郵件',
    'contractors.phone': '電話',
    'contractors.address': '地址',
    'contractors.status': '狀態',
    'contractors.operations': '操作',
    'contractors.confirmDelete': '確定要刪除此承包商嗎？',
    'contractors.status.active': '有效',
    'contractors.status.inactive': '停用',

    // Status values
    'status.approved': '已批准',
    'status.reject': '退件',
    'status.underReview': '審核中',
    'status.notSubmit': '未提交',
    'status.open': '開啟',
    'status.closed': '已關閉',
    'status.void': '廢止',

    // Checklist
    'checklist.title': '檢查表列表',
    'checklist.listTitle': '檢查表紀錄',
    'checklist.addNew': '新增檢查表',
    'checklist.searchPlaceholder': '搜尋檢查表...',
    'checklist.recordNotFound': '找不到紀錄',
    'checklist.selectNoi': '選擇 NOI',
    'checklist.status.ongoing': '進行中',
    'checklist.status.pass': '合格',
    'checklist.status.fail': '不合格',

    // ITP
    'itp.title': 'ITP 列表',
    'itp.statsTitle': '狀態統計',
    'itp.maturitySubmission': '送審成熟度 %',
    'itp.maturityApproval': '核准成熟度 %',
    'itp.addNew': '+ 新增 ITP',
    'itp.searchPlaceholder': '搜尋 ITP...',
    'itp.referenceNo': '文件編號',
    'itp.status': '狀態',
    'itp.vendor': '承攬廠商',
    'itp.description': '主旨',
    'itp.rev': '版本',
    'itp.submissionDate': '更新日期',
    'itp.editTitle': '編輯 ITP',
    'itp.addTitle': '新增 ITP',
    'itp.infoSection': 'ITP 資訊',
    'itp.selectContractor': '選擇承包商',
    'itp.revPlaceholder': '請輸入 Rev5.0 以上版本',
    'itp.revSelectCustom': 'Rev5.0 以上（手動輸入）',
    'itp.confirmDelete': '確定要刪除此 ITP 項目嗎？此操作無法復原。',
    'itp.addError': '新增失敗，請稍後再試',
    'itp.updateError': '更新失敗，請稍後再試',
    'itp.deleteError': '刪除失敗，請稍後再試',
    'itp.status.approved': '已核准',
    'itp.status.approvedWithComments': '核准但帶有意見',
    'itp.status.pending': '待審核',
    'itp.status.noSubmit': '未提交',
    'itp.status.reviseResubmit': '修訂並重新提交',
    'itp.status.rejected': '退件',
    'itp.status.void': '作廢',
    'itp.tooltip.edit': '編輯',
    'itp.tooltip.details': '查看詳情',
    'itp.tooltip.review': '審核 ITP',
    'itp.tooltip.delete': '刪除',
    'itp.tooltip.viewRelatedNOI': '查看 {count} 個相關 NOI',
    'itp.tooltip.noRelatedNOI': '無相關 NOI',
    'itp.stats.submission': '送審數',
    'itp.stats.submissionMaturity': '送審成熟度 %',
    'itp.stats.approvalMaturity': '核准成熟度 %',

    'itp.detail.title': 'ITP 詳細數據',
    'itp.detail.beforeConstruction': 'A. 施工前',
    'itp.detail.duringConstruction': 'B. 施工中',
    'itp.detail.afterConstruction': 'C. 施工後',
    'itp.detail.eventNo': '項目編號',
    'itp.detail.activity': '施工作業名稱',
    'itp.detail.standard': '管理標準/圖說規範',
    'itp.detail.acceptanceCriteria': '檢查/驗收標準',
    'itp.detail.checkTiming': '檢查時機',
    'itp.detail.inspectionMethod': '檢查方法',
    'itp.detail.frequency': '檢查頻率',
    'itp.detail.nonconformity': '不符合之處理方式',
    'itp.detail.records': '檢查紀錄表單',
    'itp.detail.verificationPoint': '檢驗點點位',
    'itp.detail.subcon': '分包商',
    'itp.detail.epci': 'EPCI',
    'itp.detail.employer': '業主',
    'itp.detail.hse': 'HSE',

    'itp.selfInspection.title': '鋼筋材料工程自主檢查表',
    'itp.selfInspection.organizingUnit': '主辦單位',
    'itp.selfInspection.supervisingUnit': '監造單位',
    'itp.selfInspection.contractor': '承攬廠商',
    'itp.selfInspection.location': '施作位置',
    'itp.selfInspection.applicationDate': '申請日期',
    'itp.selfInspection.entryType': '進場次別',
    'itp.selfInspection.entrySequence': '第次',
    'itp.selfInspection.datePlaceholder': '年 月 日',
    'itp.selfInspection.contractQty': '契約數量(噸)',
    'itp.selfInspection.previous': '前次(噸)',
    'itp.selfInspection.current': '本次(噸)',
    'itp.selfInspection.accumulated': '累計(噸)',
    'itp.selfInspection.item': '檢驗項目',
    'itp.selfInspection.brand': '廠牌',
    'itp.selfInspection.heatNo': '爐號',
    'itp.selfInspection.model': '型號',
    'itp.selfInspection.number': '號數',
    'itp.selfInspection.subtotal': '進場小計(噸)',
    'itp.selfInspection.sampleQty': '抽樣支數',
    'itp.selfInspection.total': '合計',
    'itp.selfInspection.attachments': '附件',
    'itp.selfInspection.attach.spec': '規範',
    'itp.selfInspection.attach.submission': '送審資料',
    'itp.selfInspection.attach.drawing': '圖說',
    'itp.selfInspection.attach.other': '其他 (品質保證書、無放射性證明)',
    'itp.selfInspection.q.no': '題號',
    'itp.selfInspection.q.item': '檢查項',
    'itp.selfInspection.q1': '本項進場設備材料，其廠牌型號是否符合規定',
    'itp.selfInspection.q2': '本項進場設備材料，其數量為 SD280W【 】噸；SD420W【 】噸',
    'itp.selfInspection.q3': '本項進場設備材料，其規格尺寸是否符合規定',
    'itp.selfInspection.q4': '本項進場設備材料，其顏色、附屬配件是否齊全符合要求',
    'itp.selfInspection.q5': '本項進場設備材料，其外觀是否無不當損壞',
    'itp.selfInspection.q6': '本項進場設備材料，貯放位置及保存方式是否符合要求',
    'itp.selfInspection.q7': '本項進場設備材料，其檢附資料是否齊全',
    'itp.selfInspection.q7.customs': '海關進口證明',
    'itp.selfInspection.q7.materialCert': '出廠及材質證明',
    'itp.selfInspection.q7.testReport': '出廠測試報告',
    'itp.selfInspection.q7.equipmentList': '設備清單',
    'itp.selfInspection.q7.other': '其他',
    'itp.selfInspection.auditResult': '核定結果',
    'itp.selfInspection.audit.approved': '合格',
    'itp.selfInspection.audit.resample': '重新取樣',
    'itp.selfInspection.audit.reject': '退回',
    'itp.selfInspection.sd280': 'SD280W 中拉鋼筋(#3)',
    'itp.selfInspection.sd420': 'SD420W 高拉鋼筋(#4~#8)',
    'itp.selfInspection.siteSupervisor': '工地主管簽章',
    'itp.selfInspection.fieldEngineer': '現場工程師簽章',
    'itp.selfInspection.inspectionLocation': '檢驗地點',
    'itp.selfInspection.attachedInfo': '檢附資料',
    'itp.selfInspection.deformedBar': '竹節鋼筋',
    'itp.selfInspection.coupler': '續接器',
    'itp.selfInspection.attachment.spec': '規範',
    'itp.selfInspection.attachment.submission': '送審資料',
    'itp.selfInspection.attachment.drawing': '圖說',
    'itp.selfInspection.attachment.other': '其他 (品質保證書、無放射性證明)',
    'itp.selfInspection.attachment.customs': '海關進口證明',
    'itp.selfInspection.attachment.materialCert': '出廠及材質證明',
    'itp.selfInspection.attachment.testReport': '出廠測試報告',
    'itp.selfInspection.attachment.equipmentList': '產品型錄或說明書',
    'itp.selfInspection.questionNo': '題號',
    'itp.detail.saveSuccess': 'ITP 數據已保存。',
    'itp.detail.saveError': '儲存失敗：',
    'itp.detail.saveErrorGeneric': '儲存失敗，請稍後再試。',
    'itp.detail.missingId': '無法儲存：缺少 ITP 編號',
    'common.total': '合計',
    'audit.total': '總計',
    'audit.schedule': '稽核排程',
    'audit.totalAudits': '稽核總數',

    // FollowUp
    'followup.title': '後續問題追蹤',
    'followup.listTitle': '問題列表',
    'followup.addNew': '新增問題',
    'followup.statsTitle': '狀態統計',
    'followup.editTitle': '編輯問題',
    'followup.addTitle': '新增問題',
    'followup.detailsTitle': '問題詳情',
    'followup.issueNo': '參考編號',
    'followup.status': '狀態',
    'followup.assignedTo': '指派給',
    'followup.vendor': '廠商 / 承包商',
    'followup.sourceModule': '來源模組',
    'followup.sourceRef': '來源參考編號',
    'followup.createdDate': '建立日期',
    'followup.dueDate': '到期日',
    'followup.description': '描述',
    'followup.action': '行動/處置',
    'followup.source': '來源',
    'followup.tooltip.goToModule': '前往 {module}',

    // KPI
    'kpi.title': '關鍵績效指標 (KPI)',
    'kpi.subtitle': 'KPI 依每月 PQP、ITP、OBS、NCR 結案率計算，各指標具權重。',
    'kpi.weights': '權重設定',
    'kpi.trendTitle': 'KPI 趨勢',
    'kpi.noData': '尚無月度資料，有日期的 PQP / ITP / OBS / NCR 紀錄會顯示於此。',
    'kpi.tableTitle': 'KPI 依廠商',
    'kpi.month': '月份',
    'kpi.scope': '範圍',
    'kpi.lastMonth': '上月',
    'kpi.thisMonth': '本月',
    'kpi.trend': '趨勢',
    'kpi.variance': '差異',

    // KM
    'km.title': '知識管理 (KM)',
    'km.systemTitle': '知識管理系統',
    'km.description': '此模組用於管理組織的知識資產、文件、最佳實踐和經驗分享。',

    // IAM
    'iam.title': '身份與權限管理 (IAM)',
    'iam.users': '用戶管理',
    'iam.roles': '角色管理',
    'iam.permissions': '權限預覽表',
    'iam.permissionStats': '權限統計',
    'iam.countPermissions': '{count} 個權限',
    'iam.searchUser': '搜尋用戶...',
    'iam.searchRole': '搜尋角色...',
    'iam.userList': '用戶列表',
    'iam.roleList': '角色列表',
    'iam.addUser': '新增用戶',
    'iam.addRole': '新增角色',
    'iam.editUser': '編輯用戶',
    'iam.editRole': '編輯角色',
    'iam.name': '姓名',
    'iam.email': '電子郵件',
    'iam.role': '角色',
    'iam.status': '狀態',
    'iam.description': '描述',
    'iam.permissionsLabel': '權限',
    'iam.placeholder.name': '輸入姓名',
    'iam.placeholder.email': '輸入電子郵件',
    'iam.placeholder.roleName': '輸入角色名稱',
    'iam.placeholder.roleDesc': '輸入角色描述',
    'iam.status.active': '啟用',
    'iam.status.inactive': '停用',
    'iam.perm.read': '讀取',
    'iam.perm.write': '寫入',
    'iam.perm.delete': '刪除',
    'iam.perm.manageUsers': '管理用戶',
    'iam.perm.manageRoles': '管理角色',
    'iam.permDesc.read': '允許讀取資料',
    'iam.permDesc.write': '允許寫入資料',
    'iam.permDesc.delete': '允許刪除資料',
    'iam.permDesc.manageUsers': '允許管理用戶帳號',
    'iam.permDesc.manageRoles': '允許管理角色和權限',
    'iam.password': '密碼',
    'iam.confirmPassword': '確認密碼',
    'iam.resetPassword': '重設密碼',
    'iam.createdDate': '建立日期',
    'iam.deleteError': '刪除失敗',
    'iam.fetchError': '無法取得 IAM 資料',
    'iam.passwordMismatch': '密碼不一致',
    'iam.passwordTooShort': '密碼太短（最少 8 個字元）',
    'iam.permissionsDesc': '權限說明',
    'iam.placeholder.confirmPassword': '請再次輸入密碼',
    'iam.placeholder.password': '請輸入密碼（最少 8 個字元）',
    'iam.roleName': '角色名稱',
    'iam.saveRoleError': '儲存角色失敗',
    'iam.saveUserError': '儲存用戶失敗',
  }, // Close zh
}; // Close translations

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get language from localStorage or default to 'en'
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh') ? savedLanguage : 'en';
  });

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([paramsKey, value]) => {
        translation = translation.replace(new RegExp(`{${paramsKey}}`, 'g'), String(value));
      });
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
